tree: Events
era: 2016Post
envPath: /cvmfs/cms.cern.ch/cmsset_default.sh
jobDir: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final
exeToRun: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/hzana.exe
outDir: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/outputBkg/output_Z
commonInfo:
  - hlt 4
  - maxEvent -1
  - intLumi 35930
  - xsec 0.0794
  - useLumiWt 1
  - usePu_wt 1
  - useGen_wt 0
  - usePU_gen_wt 0
  - useTlumi_wt 0
  - useTlumi_wt_hasGen 0
  - find_SU 1
  - year 16
  - isPre False
mvaInfo:
#mvaSkimFile data2018H_MuEG_hist_skim.root
  - readMVA 0
  - mvAlgo BDTG
  - mvaXMLFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/ML/BDTG/TMVAClassification_BDTG.weights.xml
skimInfo:
  - createMVATree 0
samplesDict:
  Signal:  
    ### ZtoMuMuG
    ZtoMuMuG_2016Post:
      filedirs: 
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2016/mc/postvfp/ZGTo2MuG_mll_2to15_LO_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/221123_135523/0000
      filesPerJob: 50
      group: 'ZBkg'
