tree: Events
era: 2018
envPath: /cvmfs/cms.cern.ch/cmsset_default.sh
jobDir: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final
exeToRun: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/higgsana.exe
outDir: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/outputSignal/output_H
commonInfo:
  - hlt 0
  - maxEvent -1
  - intLumi 59830
  - useLumiWt 1
  - usePu_wt 1
  - useGen_wt 0
  - usePU_gen_wt 0
  - useTlumi_wt 0
  - useTlumi_wt_hasGen 0
  - find_SU 1
  - year 18
mvaInfo:
#mvaSkimFile data2018H_MuEG_hist_skim.root
  - readMVA 0
  - mvAlgo BDTG
  - mvaXMLFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/ML/BDTG/TMVAClassification_BDTG.weights.xml
skimInfo:
  - createMVATree 0
samplesDict:
  Signal:  
    ### HtoJPsiG
    HtoJPsiG_GluGlu_2018:
      filedirs: 
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/GluGluToH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_131727/0000
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/GluGluToH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132201/0000
      xsec: 0.000008570
      filesPerJob: 50
      group: 'HSignal'
    HtoJPsiG_VBF_2018:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/VBFToH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220521_101039/0000
      xsec: 0.000000661
      filesPerJob: 50
      group: 'HSignal'
    HtoJPsiG_WH_2018:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/WH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132223/0000
      xsec: 0.000000243
      filesPerJob: 50
      group: 'HSignal'
    HtoJPsiG_ZH_2018:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/ZH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132650/0000
      xsec: 0.000000153
      filesPerJob: 50
      group: 'HSignal'
    HtoJPsiG_TTH_2018:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/TTH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132752/0000
      xsec: 0.0000000897
      filesPerJob: 50
      group: 'HSignal'
    HtoJPsiG_BBH_2018:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000
      xsec: 0.00000008913
      filesPerJob: 50
      group: 'HSignal'


