tree: Events
era: 2018
envPath: /cvmfs/cms.cern.ch/cmsset_default.sh
jobDir: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final
exeToRun: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/hzana.exe
outDir: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/outputData/output_Z
commonInfo:
  - hlt 0
  - maxEvent -1
  - year 18
mvaInfo:
#mvaSkimFile data2018H_MuEG_hist_skim.root
  - readMVA 0
  - mvAlgo BDTG
  - mvaXMLFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/ML/BDTG/TMVAClassification_BDTG.weights.xml
skimInfo:
  - createMVATree 0
samplesDict:
  DATA:  
    ### MuonEG
    MuonEG_2018_taskA:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/data/MuonEG/Run2018A-UL2018_MiniAODv2_NanoAODv9-v1/230317_001951/0000
      filesPerJob: 4
      group: 'data'
    MuonEG_2018_taskB:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/data/MuonEG/Run2018B-UL2018_MiniAODv2_NanoAODv9-v1/230317_002102/0000
      filesPerJob: 4
      group: 'data'
    MuonEG_2018_taskC:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/data/MuonEG/Run2018C-UL2018_MiniAODv2_NanoAODv9-v1/230317_002213/0000
      filesPerJob: 4
      group: 'data'
    MuonEG_2018_taskD:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/data/MuonEG/Run2018D-UL2018_MiniAODv2_NanoAODv9-v1/230317_002324/0000
      filesPerJob: 4
      group: 'data'
