START
era 2018
dataType mc#signal
hlt 0
maxEvent -1
intLumi 59830
useLumiWt 1
usePu_wt 1
useGen_wt 0
usePU_gen_wt 0
useTlumi_wt 0
useTlumi_wt_hasGen 0
find_SU 1
year 18
############ Skim Info ###############
createMVATree 0
############ MVA Info ###############
readMVA 0
mvAlgo BDTG
mvaXMLFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/ML/BDTG/TMVAClassification_BDTG.weights.xml
mvaSkimFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/outputSignal/output_H/muup/HtoJPsiG_BBH_2018_skim.root
########### xsec, hist ###########
xsec 8.913e-08
histFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/outputSignal/output_H/muup/HtoJPsiG_BBH_2018_hist.root
############ Cut lists ###############
############ Input Files ##############
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_1.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_10.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_11.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_12.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_2.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_3.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_4.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_5.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_6.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_7.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_8.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/BBH_HToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/220506_132720/0000/tree_9.root
########################################
END