START
era 2018
dataType mc#signal
hlt 0
maxEvent -1
intLumi 59830
xsec 0.0794
useLumiWt 1
usePu_wt 1
useGen_wt 0
usePU_gen_wt 0
useTlumi_wt 0
useTlumi_wt_hasGen 0
find_SU 1
year 18
isPre False
############ Skim Info ###############
createMVATree 0
############ MVA Info ###############
readMVA 0
mvAlgo BDTG
mvaXMLFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/ML/BDTG/TMVAClassification_BDTG.weights.xml
mvaSkimFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/outputBkg/output_Z/nominal/ZtoMuMuG_2018_skim.root
########### xsec,lumi,hist ###########
histFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/outputBkg/output_Z/nominal/ZtoMuMuG_2018_hist.root
############ Cut lists ###############
############ Input Files ##############
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/ZGTo2MuG_mll_2to15_LO_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/221123_153749/0000/tree_1.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2018/mc/ZGTo2MuG_mll_2to15_LO_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/221123_153749/0000/tree_2.root
########################################
END