START
era 2016Pre
dataType mc#signal
hlt 4
maxEvent -1
intLumi 19480
xsec 0.000318
useLumiWt 1
usePu_wt 1
useGen_wt 0
usePU_gen_wt 0
useTlumi_wt 0
useTlumi_wt_hasGen 0
find_SU 1
year 16
isPre True
############ Skim Info ###############
createMVATree 0
############ MVA Info ###############
readMVA 0
mvAlgo BDTG
mvaXMLFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/ML/BDTG/TMVAClassification_BDTG.weights.xml
mvaSkimFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/outputSignal/output_Z/scaledown/ZtoJPsiG_2016Pre_skim.root
########### xsec,lumi,hist ###########
histFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/outputSignal/output_Z/scaledown/ZtoJPsiG_2016Pre_hist.root
############ Cut lists ###############
############ Input Files ##############
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2016/mc/prevfp/ZToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/220506_115555/0000/tree_1.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2016/mc/prevfp/ZToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/220506_115555/0000/tree_2.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2016/mc/prevfp/ZToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/220506_115555/0000/tree_3.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2016/mc/prevfp/ZToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/220506_115555/0000/tree_4.root
inputFile /eos/user/s/sbaradia2/HZJPsiGamma/store/y2016/mc/prevfp/ZToJPsiG_JPsiToMuMu_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/220506_115555/0000/tree_5.root
########################################
END