tree: Events
era: 2017
envPath: /cvmfs/cms.cern.ch/cmsset_default.sh
jobDir: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final
exeToRun: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/higgsana.exe
outDir: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/outputBkg/output_H
commonInfo:
  - hlt 0
  - maxEvent -1
  - intLumi 27070
  - useLumiWt 1
  - usePu_wt 1
  - useGen_wt 0
  - usePU_gen_wt 0
  - useTlumi_wt 0
  - useTlumi_wt_hasGen 0
  - find_SU 1
  - year 17
mvaInfo:
#mvaSkimFile data2017H_MuEG_hist_skim.root
  - readMVA 0
  - mvAlgo BDTG
  - mvaXMLFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/ML/BDTG/TMVAClassification_BDTG.weights.xml
skimInfo:
  - createMVATree 0
samplesDict:
  MC:  
    ### HtoMuMuG
    HtoMuMuG_GluGlu_2017:
      filedirs: 
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2017/mc/GluGluHToMuMuG_M125_Dalitz_012j_TuneCP5_13TeV_amcatnlo_pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/221123_142051/0000
      xsec: 0.00190
      filesPerJob: 50
      group: 'HBkg'
    HtoMuMuG_VBF_2017:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2017/mc/VBFHToMuMuG_M125_Dalitz_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/221123_142114/0000
      xsec: 0.000146
      filesPerJob: 50
      group: 'HBkg'
    HtoMuMuG_WH_2017:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2017/mc/WHToMuMuG_M125_Dalitz_012j_TuneCP5_13TeV_amcatnloFXFX_pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/221123_142159/0000
      xsec: 0.0000541
      filesPerJob: 50
      group: 'HBkg'
    HtoMuMuG_ZH_2017:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2017/mc/ZHToMuMuG_M125_Dalitz_012j_TuneCP5_13TeV_amcatnloFXFX_pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/221123_142137/0000
      xsec: 0.0000340
      filesPerJob: 50
      group: 'HBkg'