tree: Events
era: 2016Pre
envPath: /cvmfs/cms.cern.ch/cmsset_default.sh
jobDir: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final
exeToRun: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/higgsana.exe
outDir: /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/outputBkg/output_H
commonInfo:
  - hlt 4
  - maxEvent -1
  - intLumi 35930
  - useLumiWt 1
  - usePu_wt 1
  - useGen_wt 0
  - usePU_gen_wt 0
  - useTlumi_wt 0
  - useTlumi_wt_hasGen 0
  - find_SU 1
  - year 16
  - isPre True
mvaInfo:
#mvaSkimFile data2016H_MuEG_hist_skim.root
  - readMVA 0
  - mvAlgo BDTG
  - mvaXMLFile /afs/cern.ch/work/s/sbaradia/public/Analysis/HZtoJPsiGamma_final/ML/BDTG/TMVAClassification_BDTG.weights.xml
skimInfo:
  - createMVATree 0
samplesDict:
  MC:  
    ### HtoMuMuG
    HtoMuMuG_GluGlu_2016Pre:
      filedirs: 
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2016/mc/prevfp/GluGluHToMuMuG_M125_Dalitz_012j_TuneCP5_13TeV_amcatnlo_pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/221123_134326/0000
      xsec: 0.00190
      filesPerJob: 50
      group: 'HBkg'
    HtoMuMuG_VBF_2016Pre:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2016/mc/prevfp/VBFHToMuMuG_M125_Dalitz_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/221123_134428/0000
      xsec: 0.000146
      filesPerJob: 50
      group: 'HBkg'
    HtoMuMuG_WH_2016Pre:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2016/mc/prevfp/WHToMuMuG_M125_Dalitz_012j_TuneCP5_13TeV_amcatnloFXFX_pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/221123_134639/0000
      xsec: 0.0000541
      filesPerJob: 50
      group: 'HBkg'
    HtoMuMuG_ZH_2016Pre:
      filedirs:
        - /eos/user/s/sbaradia2/HZJPsiGamma/store/y2016/mc/prevfp/ZHToMuMuG_M125_Dalitz_012j_TuneCP5_13TeV_amcatnloFXFX_pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/221123_134537/0000
      xsec: 0.0000340
      filesPerJob: 50
      group: 'HBkg'